export default function AffiliateDisclosure() {
  return (
    <div className="py-16 px-4">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-8 text-white text-center">Affiliate Disclosure</h1>

        <p className="text-xl text-gray-300 text-center mb-12 leading-relaxed">
          Transparency about how PlayersEdge Group earns revenue and operates.
        </p>

        {/* Main Disclosure */}
        <div className="bg-gradient-to-r from-slate-800 to-slate-700 border-l-4 border-lime-500 rounded-lg p-8 mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-white">Affiliate Relationship Disclosure</h2>
          <p className="text-gray-300 leading-relaxed mb-4">
            PlayersEdge Group operates as an <strong className="text-white">affiliate marketing partner</strong> for
            licensed online sportsbook operators in the United States.
          </p>
          <p className="text-gray-300 leading-relaxed mb-4">
            When you click on links to sportsbooks on our website or through our marketing channels
            and subsequently sign up, create an account, or make a deposit with those operators,
            PlayersEdge Group <strong className="text-white">may receive compensation</strong> from the sportsbook.
          </p>
          <p className="text-gray-300 leading-relaxed">
            This disclosure is provided in accordance with the Federal Trade Commission's guidelines
            on endorsements and testimonials, as well as state regulations governing affiliate marketing
            in the online gambling industry.
          </p>
        </div>

        {/* How We Earn */}
        <div className="bg-slate-800 rounded-lg p-8 mb-8">
          <h2 className="text-2xl font-semibold mb-6 text-white">How We Earn Revenue</h2>
          <p className="text-gray-300 mb-6">
            PlayersEdge Group may receive compensation from licensed sportsbook operators through various
            affiliate commission structures, including:
          </p>

          <div className="space-y-6">
            <div>
              <h3 className="text-xl font-semibold text-white mb-3">Cost Per Acquisition (CPA)</h3>
              <p className="text-gray-300 leading-relaxed">
                A one-time payment made by the sportsbook when a user referred by PlayersEdge Group
                completes a qualifying action, such as creating an account, making a first deposit,
                or placing a first bet. The specific qualifying criteria vary by operator.
              </p>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-white mb-3">Revenue Share</h3>
              <p className="text-gray-300 leading-relaxed">
                An ongoing percentage of the net gaming revenue generated by users referred by
                PlayersEdge Group. Revenue share payments continue as long as the referred user
                remains active with the sportsbook.
              </p>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-white mb-3">Hybrid Models</h3>
              <p className="text-gray-300 leading-relaxed">
                Some affiliate agreements combine CPA and revenue share, providing both an initial
                acquisition payment and ongoing revenue participation.
              </p>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-white mb-3">Fixed Fees or Sponsorships</h3>
              <p className="text-gray-300 leading-relaxed">
                In some cases, we may receive fixed monthly fees or sponsorship payments from
                operators for featuring their brand or content on our platforms.
              </p>
            </div>
          </div>
        </div>

        {/* What This Means */}
        <div className="bg-slate-800 rounded-lg p-8 mb-8">
          <h2 className="text-2xl font-semibold mb-6 text-white">What This Means for You</h2>
          <div className="space-y-4">
            <div className="flex items-start">
              <span className="text-lime-500 mr-4 text-2xl font-bold">✓</span>
              <div>
                <h3 className="text-lg font-semibold text-white mb-2">Your Experience Is Unchanged</h3>
                <p className="text-gray-300">
                  The affiliate commission we receive does not affect the welcome offers, promotions,
                  odds, or any other terms you receive from the sportsbook. You get the same deal
                  whether you come through our link or go directly to the operator.
                </p>
              </div>
            </div>

            <div className="flex items-start">
              <span className="text-lime-500 mr-4 text-2xl font-bold">✓</span>
              <div>
                <h3 className="text-lg font-semibold text-white mb-2">No Additional Cost to You</h3>
                <p className="text-gray-300">
                  You do not pay anything extra when you sign up through our links. The commission
                  is paid by the sportsbook operator as a marketing expense, not by you.
                </p>
              </div>
            </div>

            <div className="flex items-start">
              <span className="text-lime-500 mr-4 text-2xl font-bold">✓</span>
              <div>
                <h3 className="text-lg font-semibold text-white mb-2">Editorial Independence</h3>
                <p className="text-gray-300">
                  While we have financial relationships with the sportsbooks we feature, our goal
                  is to provide accurate, helpful information. We strive to present offers and
                  comparisons in an unbiased manner based on publicly available terms and conditions.
                </p>
              </div>
            </div>

            <div className="flex items-start">
              <span className="text-lime-500 mr-4 text-2xl font-bold">✓</span>
              <div>
                <h3 className="text-lg font-semibold text-white mb-2">Your Choice</h3>
                <p className="text-gray-300">
                  Whether or not to sign up with any sportsbook featured on our site is entirely
                  your decision. We encourage you to read the full terms and conditions of any offer
                  before creating an account.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* What We Are Not */}
        <div className="bg-slate-800 rounded-lg p-8 mb-8">
          <h2 className="text-2xl font-semibold mb-6 text-white">What PlayersEdge Group Is NOT</h2>
          <div className="space-y-3 text-gray-300">
            <p className="flex items-start">
              <span className="text-red-400 mr-3 font-bold text-lg">✗</span>
              <span>
                We are <strong className="text-white">not a sportsbook operator</strong>. We do not accept or process wagers.
              </span>
            </p>
            <p className="flex items-start">
              <span className="text-red-400 mr-3 font-bold text-lg">✗</span>
              <span>
                We are <strong className="text-white">not a payment processor</strong>. We do not handle deposits, withdrawals, or player funds.
              </span>
            </p>
            <p className="flex items-start">
              <span className="text-red-400 mr-3 font-bold text-lg">✗</span>
              <span>
                We are <strong className="text-white">not a gambling platform</strong>. All gambling activity occurs directly between you and the licensed operator.
              </span>
            </p>
            <p className="flex items-start">
              <span className="text-red-400 mr-3 font-bold text-lg">✗</span>
              <span>
                We are <strong className="text-white">not responsible for operator actions</strong>. Each sportsbook is independently responsible for its own customer service, compliance, and operations.
              </span>
            </p>
          </div>
        </div>

        {/* Compliance */}
        <div className="bg-slate-800 rounded-lg p-8 mb-8">
          <h2 className="text-2xl font-semibold mb-6 text-white">Our Compliance Commitment</h2>
          <p className="text-gray-300 mb-4">
            PlayersEdge Group is committed to operating in full compliance with all applicable laws
            and regulations, including:
          </p>
          <ul className="space-y-2 text-gray-300 ml-6">
            <li className="flex items-start">
              <span className="text-lime-500 mr-3">•</span>
              <span>Federal Trade Commission (FTC) guidelines on endorsements and testimonials</span>
            </li>
            <li className="flex items-start">
              <span className="text-lime-500 mr-3">•</span>
              <span>State-level regulations governing affiliate marketing for online gambling</span>
            </li>
            <li className="flex items-start">
              <span className="text-lime-500 mr-3">•</span>
              <span>Responsible gambling and consumer protection standards</span>
            </li>
            <li className="flex items-start">
              <span className="text-lime-500 mr-3">•</span>
              <span>Age and location restrictions (21+ and legal jurisdictions only)</span>
            </li>
          </ul>
        </div>

        {/* Your Rights */}
        <div className="bg-slate-800 rounded-lg p-8 mb-8">
          <h2 className="text-2xl font-semibold mb-6 text-white">Your Rights and Responsibilities</h2>
          <p className="text-gray-300 mb-4">
            When considering whether to sign up with a sportsbook through our links, please remember:
          </p>
          <ul className="space-y-2 text-gray-300 ml-6">
            <li className="flex items-start">
              <span className="text-lime-500 mr-3">•</span>
              <span>You should only sign up if online sports betting is legal in your jurisdiction.</span>
            </li>
            <li className="flex items-start">
              <span className="text-lime-500 mr-3">•</span>
              <span>You must be at least 21 years old.</span>
            </li>
            <li className="flex items-start">
              <span className="text-lime-500 mr-3">•</span>
              <span>Read all terms and conditions carefully before creating an account or claiming any offer.</span>
            </li>
            <li className="flex items-start">
              <span className="text-lime-500 mr-3">•</span>
              <span>Gambling should be treated as entertainment, not as a way to make money.</span>
            </li>
            <li className="flex items-start">
              <span className="text-lime-500 mr-3">•</span>
              <span>If you or someone you know has a gambling problem, call 1-800-GAMBLER (1-800-426-2537).</span>
            </li>
          </ul>
        </div>

        {/* Questions */}
        <div className="bg-gradient-to-r from-slate-800 to-slate-700 rounded-lg p-8">
          <h2 className="text-2xl font-semibold mb-4 text-white">Questions or Concerns?</h2>
          <p className="text-gray-300 leading-relaxed mb-4">
            If you have questions about our affiliate relationships, how we earn revenue, or any
            other aspect of our business operations, please contact us.
          </p>
          <a
            href="/contact"
            className="inline-block bg-lime-500 hover:bg-lime-600 text-slate-900 font-semibold px-8 py-3 rounded-lg transition-colors"
          >
            Contact Us
          </a>
        </div>
      </div>
    </div>
  );
}
